### ISSUE TITLE
Proposal: Add :verified: custom emoji

### ISSUE THREAD

**Issue by pinpox** [chaossocial/custom#14]
I've seen various instances adding the :verified: custom emoji, which I found hilarious. Would it be possible to add it tho chaos.social as well? Here is an example:

![image](https://user-images.githubusercontent.com/1719781/201480676-e98570c3-0542-44b4-b262-527be675453e.png)

The svg can be found [here](https://assets.chaos.social/cache/custom_emojis/images/000/268/884/original/81b87bd557b64de7.png
) though a blue version would make more sense.

**Comment by leahoswald** [comment]
Sorry we normally don't add custom emojis on request.

**Comment by pinpox** [comment]
Ok, i understand. If you change your mind, let me know where to submit a PR :)
