### ISSUE TITLE
dark & chaos-social-wide theme don't show embedded youtube videos correctly

### ISSUE THREAD

**Issue by sjn** [chaossocial/custom#15]
Hei!

I'm using the chaos-social-wide theme in my profile settings, and see that embedded youtube videos (and I think some other embedded audio apps, iirc) don't show properly.

This problem doesn't exist with the mastodon-light theme.

The following two screenshots are with the chaos-social-wide theme:

![Screenshot 2024-06-08 at 06-32-26 chaos social](https://github.com/chaossocial/custom/assets/54637/8eadeceb-a134-4fb7-8120-413f2f59e2b3)
![Screenshot 2024-06-08 at 06-33-28 chaos social](https://github.com/chaossocial/custom/assets/54637/5eb03351-a37c-41e2-9cd5-35d68a2dc3a8)

And these are with the mastodon-light theme:

![Screenshot 2024-06-08 at 06-36-27 chaos social](https://github.com/chaossocial/custom/assets/54637/2b4b8647-f5d0-44a0-9eb6-ef5b10bc5db4)
![Screenshot 2024-06-08 at 06-36-48 chaos social](https://github.com/chaossocial/custom/assets/54637/5a5de6f9-d3a3-40d6-9016-c0b72e9a0a1c)

The same issue applies to the "default" dark theme. I haven't tested the "contrast" theme.

My browser is Firefox 126.0 running on Ubuntu Linux 24.04 LTS.

Hope this is enough info for you to troubleshoot this! And thanks for running this Mastodon server! Super appreciated. :-D

**Comment by leahoswald** [comment]
I'll check this later

**Comment by sjn** [comment]
Thank you for merging; The site works now for me as expected.
