### ISSUE TITLE
Mentions & Hashtags sollten sich vom normalen Text abheben

### ISSUE THREAD

**Issue by mweinelt** [chaossocial/custom#6]
Toots mit vielen Mentions sind arg unübersichtlich, da man lange nach dem Inhalt sucht zwischen all den Mentions. Auch Hashtags sind nicht direkt zu erkennen.

Bspw.:
http://f.praschnig.com/display/b8c357bb835a5a34a8c8022440108091

Twitter verwendet dafür bspw. `#8bd`, was als Blauton sehr gut für Links funktioniert.

**Comment by rixx** [comment]
Classes an mentions: `u-url mention status-link`
Classes an hashtags: `mention hashtag status-link`
Classes an urls: `status-link`
